default_context:
  project_name: 'CryptoLion'
  project_slug: 'CryptoLion'
  domain_main: 'CryptoLion.com'
  domain_staging: 'stag.CryptoLion.com'
  docker_swarm_stack_name_main: 'CryptoLion-com'
  docker_swarm_stack_name_staging: 'stag-CryptoLion-com'
  secret_key: '254d8f2e812009b531f7e37bcba57d00580d5c9e51a00139455961c5de9f01e2'
  first_superuser: '58d5377b9bd2ef4409448faeb52ee48b594d273c357287358b1896df7c735c6c'
  first_superuser_password: '4ec2c194d8372ebee8297bfb1758effd83f0c90e2e2c03f1473e04bba61bf0f5'
  backend_cors_origins: 'dev.CryptoLion.com'
  smtp_port: '587'
  smtp_host: 'smtp.mail.yahoo.com'
  smtp_user: 'mosesjoe@yahoo.com'
  smtp_password: '00001234gh'
  smtp_emails_from_email: 'mosesjoe@yahoo.com'
  postgres_password: 'mosesjoe@yahoo.com'
  pgadmin_default_user: 'sechmos'
  pgadmin_default_user_password: 'sechmos'
  traefik_constraint_tag: 'CryptoLion.com'
  traefik_constraint_tag_staging: 'stag.CryptoLion.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:4ec2c194d8372ebee8297bfb1758effd83f0c90e2e2c03f1473e04bba61bf0f5'
  sentry_dsn: ''
  docker_image_prefix: 'crypto'
  docker_image_backend: 'cryptobackend'
  docker_image_celeryworker: 'cryptoceleryworker'
  docker_image_frontend: 'cryptofrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
